version: 2
project_name: musicalc

before:
  hooks:
    - git pull && git checkout -- go.mod && git fetch --tags --force
#    - go mod tidy

builds:
  - id: win-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - CGO_CFLAGS=-O3 -flto=auto -march=x86-64-v3 -m64
      - CGO_LDFLAGS=-O3 -flto=auto
    goos: [windows]
    goarch: [amd64]
    goamd64: [v3]
    ldflags:
      - -s -w -H=windowsgui
    binary: musicalc_x64
    # This keeps the binary at the top level of the dist folder
    no_unique_dist_dir: true

  - id: win-arm64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-windows-gnu
      - CXX=zig c++ -target aarch64-windows-gnu
      - CGO_CFLAGS=-O3 -mcpu=oryon_1 -fomit-frame-pointer
      - CGO_LDFLAGS=-O3
    goos: [windows]
    goarch: [arm64]
    ldflags:
      - -s -w -H=windowsgui
    binary: musicalc_arm64
    no_unique_dist_dir: true

archives:
  - id: binary-only
    # Change 'format' to 'formats' and use a list []
    formats: [binary]
    name_template: "{{ .Binary }}"
    # This prevents GoReleaser from adding default README/LICENSE files
    files:
      - none*