version: 2
project_name: musicalc

before:
  hooks:
    - go mod tidy

builds:
  - id: windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos: [windows]
    goarch: [amd64]
    ldflags:
      - -s -w -H=windowsgui
    binary: musicalc_x64
    # This keeps the binary at the top level of the dist folder
    no_unique_dist_dir: true

  - id: windows-arm64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-windows-gnu
      - CXX=zig c++ -target aarch64-windows-gnu
    goos: [windows]
    goarch: [arm64]
    ldflags:
      - -s -w -H=windowsgui
    binary: musicalc_arm64
    no_unique_dist_dir: true

# In v2, if you want just binaries, you can often omit the archives section.
# If you still need it to ensure they are treated as "release artifacts":
archives:
  - format: binary
    # We use name_template to ensure the file name remains what we want
    name_template: "{{ .Binary }}"
    # Providing a dummy file prevents GoReleaser from adding default README/LICENSE
    files:
      - none*