version: 2
project_name: musicalc

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

# This creates the .tar.gz bundle
archives:
  - files:
      - src: "install.sh"
      - src: "icons/appicon.png"
        dst: "icon.png"
      - src: "musicalc.desktop"

# This creates the .deb and .rpm "Installers"
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/bzeiss/musicalc
    maintainer: B. Zeiss <ben@zeiss.net>
    description: Music Calculator Utility
    formats:
      - deb
      - rpm
    
    # This tells Linux where to put the files on the user's system
    contents:
      - src: icons/appicon.png
        dst: /usr/share/icons/hicolor/512x512/apps/musicalc.png
      
      # This creates the Start Menu entry automatically (uses /usr/bin path)
      - src: musicalc-pkg.desktop
        dst: /usr/share/applications/musicalc.desktop
        type: config