#!/usr/bin/env python3
"""
Generate tabicons.go by bundling SVG icon files using fyne bundle.
Also generates icons.go with exported resource wrappers.
This script automates the process of creating Fyne resource bundles from SVG files.
"""

import os
import subprocess
import sys
from pathlib import Path

# Configuration constants
TARGET_PACKAGE = "ui"
TARGET_FILENAME = "tabicons.go"
RESOURCES_FILENAME = "icons.go"
OUTPUT_DIRECTORY = "internal/ui"


def get_project_root():
    """
    Find the project root directory relative to this script's location.
    Assumes script is in utils/ and project root is 1 level up.
    """
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent
    return project_root


def filename_to_resource_name(filename):
    """
    Convert SVG filename to Go resource variable name to match fyne bundle output.
    Examples:
      timecode.svg -> resourceTimecodeSvg
      freq2note.svg -> resourceFreq2noteSvg
      note-2-freq.svg -> resourceNote2FreqSvg
    
    Fyne bundle naming rules:
    - Split on hyphens
    - Remove underscores from each part
    - Capitalize first letter of parts after hyphens
    - Capitalize overall first letter
    """
    # Remove .svg extension
    name = filename.replace('.svg', '')
    
    # Split on hyphens
    parts = name.split('-')
    
    # Process each part: remove underscores, capitalize if not first part
    processed = []
    for i, part in enumerate(parts):
        # Remove underscores
        part = part.replace('_', '')
        # Capitalize first letter if this part came after a hyphen
        if i > 0 and part:
            part = part[0].upper() + part[1:]
        processed.append(part)
    
    # Join all parts
    name = ''.join(processed)
    
    # Capitalize overall first letter
    name = name[0].upper() + name[1:] if name else ''
    
    return f"resource{name}Svg"


def filename_to_exported_name(filename):
    """
    Convert SVG filename to exported Go resource name.
    Examples:
      timecode.svg -> ResourceTimecodeSvg
      freq2note.svg -> ResourceFreq2noteSvg
    """
    name = filename_to_resource_name(filename)
    # Change first 'r' to 'R' to export
    return 'R' + name[1:]


def generate_resources_file(svg_files, output_directory):
    """
    Generate icons.go with exported resource wrappers.
    """
    resources_file = output_directory / RESOURCES_FILENAME
    
    # Build the file content
    lines = [
        'package ui',
        '',
        'import "fyne.io/fyne/v2"',
        '',
        '// Exported icon resources (wrappers around bundled resources from tabicons.go)',
        '// Note: tabicons.go is auto-generated - do not modify it directly',
        '// This file is also auto-generated by utils/generate-tabicons.py',
        'var (',
    ]
    
    # Add resource exports
    for svg_file in svg_files:
        exported_name = filename_to_exported_name(svg_file)
        internal_name = filename_to_resource_name(svg_file)
        lines.append(f'\t{exported_name} = {internal_name}')
    
    lines.append(')')
    lines.append('')
    lines.append('// Ensure variables are of correct type at compile time')
    
    if svg_files:
        lines.append(f'var _ *fyne.StaticResource = {filename_to_exported_name(svg_files[0])}')
    
    lines.append('')
    
    # Write the file
    content = '\n'.join(lines)
    resources_file.write_text(content, encoding='utf-8')
    
    print(f"\n✓ Generated {RESOURCES_FILENAME}")
    print(f"  Location: {resources_file}")
    print(f"  Exported {len(svg_files)} icon resources")


def main():
    """Main execution function."""
    # Get project root
    project_root = get_project_root()
    print(f"Project root: {project_root}")
    
    # Construct paths
    svg_directory = project_root / OUTPUT_DIRECTORY
    output_file = svg_directory / TARGET_FILENAME
    
    # Verify SVG directory exists
    if not svg_directory.exists():
        print(f"Error: SVG directory does not exist: {svg_directory}")
        sys.exit(1)
    
    print(f"SVG directory: {svg_directory}")
    
    # Collect all SVG files from the directory
    svg_files = sorted([f.name for f in svg_directory.glob("*.svg")])
    
    if not svg_files:
        print(f"Error: No SVG files found in {svg_directory}")
        sys.exit(1)
    
    print(f"Found {len(svg_files)} SVG files: {', '.join(svg_files)}\n")
    
    # Remove existing output file if it exists
    if output_file.exists():
        output_file.unlink()
        print(f"Removed existing {TARGET_FILENAME}")
    
    # Change to the SVG directory
    os.chdir(svg_directory)
    print(f"Changed directory to: {svg_directory}\n")
    
    # Bundle SVG files
    for index, svg_file in enumerate(svg_files):
        is_first = (index == 0)
        
        # Build fyne bundle command
        cmd = ["fyne", "bundle", "-package", TARGET_PACKAGE]
        
        if not is_first:
            cmd.append("-append")
        
        cmd.extend(["-o", TARGET_FILENAME, svg_file])
        
        # Execute command
        print(f"Bundling {svg_file}{'...' if is_first else ' (append)...'}")
        try:
            result = subprocess.run(cmd, check=True, capture_output=True, text=True)
            if result.stdout:
                print(result.stdout)
        except subprocess.CalledProcessError as e:
            print(f"Error bundling {svg_file}: {e.stderr}")
            sys.exit(1)
    
    print(f"\n✓ Successfully generated {TARGET_FILENAME}")
    print(f"  Location: {output_file}")
    print(f"  Bundled {len(svg_files)} SVG icons")
    
    # Generate icons.go
    generate_resources_file(svg_files, svg_directory)


if __name__ == "__main__":
    main()
