#!/usr/bin/env python3
"""
Generate sclbundle.go by bundling SCL scale files using fyne bundle.
Also generates scl_resources.go with exported resource wrappers.
This script automates the process of creating Fyne resource bundles from SCL files.
"""

import os
import subprocess
import sys
from pathlib import Path

# Configuration constants
TARGET_PACKAGE = "logic"
TARGET_FILENAME = "sclbundle.go"
RESOURCES_FILENAME = "scl_resources.go"
OUTPUT_DIRECTORY = "internal/logic/scl"  # Both generated files go here (next to .scl files)
DEFAULT_SCALE = "tet-12.scl"  # Default scale file


def get_project_root():
    """
    Find the project root directory relative to this script's location.
    Assumes script is in utils/ and project root is 1 level up.
    """
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent
    return project_root


def filename_to_resource_name(filename):
    """
    Convert SCL filename to Go resource variable name to match fyne bundle output.
    Examples:
      tet-12.scl -> resourceTet12Scl
      carlos_alpha.scl -> resourceCarlosalphaScl
      bohlen-p.scl -> resourceBohlenPScl
      arabic_bayati_and_bayati-shuri_on_d.scl -> resourceArabicbayatiandbayatiShuriondScl
    
    Fyne bundle naming rules:
    - Split on hyphens
    - Remove underscores from each part
    - Capitalize first letter of parts after hyphens
    - Capitalize overall first letter
    """
    # Remove .scl extension
    name = filename.replace('.scl', '')
    
    # Split on hyphens
    parts = name.split('-')
    
    # Process each part: remove underscores, capitalize if not first part
    processed = []
    for i, part in enumerate(parts):
        # Remove underscores
        part = part.replace('_', '')
        # Capitalize first letter if this part came after a hyphen
        if i > 0 and part:
            part = part[0].upper() + part[1:]
        processed.append(part)
    
    # Join all parts
    name = ''.join(processed)
    
    # Capitalize overall first letter
    name = name[0].upper() + name[1:] if name else ''
    
    return f"resource{name}Scl"


def filename_to_exported_name(filename):
    """
    Convert SCL filename to exported Go resource name.
    Examples:
      tet-12.scl -> ResourceTet12Scl
      carlos_alpha.scl -> ResourceCarlosAlphaScl
    """
    name = filename_to_resource_name(filename)
    # Change first 'r' to 'R' to export
    return 'R' + name[1:]


def parse_scl_tuning_name(scl_path):
    """
    Parse an SCL file to extract its tuning name (description line).
    SCL format:
      - Lines starting with ! are comments
      - First non-comment, non-empty line is the description/tuning name
      - Next line is the number of notes
    Returns the tuning name or the filename if parsing fails.
    """
    try:
        # Read the SCL file
        with open(scl_path, 'r', encoding='utf-8', errors='ignore') as f:
            lines = f.readlines()
        
        # Find first non-comment, non-empty line (this is the description)
        for line in lines:
            stripped = line.strip()
            # Skip empty lines and comment lines starting with !
            if stripped and not stripped.startswith('!'):
                return stripped
        
        # Fallback to filename if no description found
        return scl_path.stem
    except Exception as e:
        print(f"Warning: Could not parse {scl_path.name}: {e}")
        return scl_path.stem


def generate_resources_file(scl_files, output_directory, default_scale):
    """
    Generate scl_resources.go with a map of tuning names to filenames.
    """
    resources_file = output_directory / RESOURCES_FILENAME
    
    # Parse all SCL files to extract tuning names
    print("\nParsing SCL files to extract tuning names...")
    tuning_map = {}
    for scl_file in scl_files:
        scl_path = output_directory / scl_file
        tuning_name = parse_scl_tuning_name(scl_path)
        tuning_map[tuning_name] = scl_file
        print(f"  {scl_file}: '{tuning_name}'")
    
    # Build the file content
    lines = [
        'package logic',
        '',
        'import "fyne.io/fyne/v2"',
        '',
        '// SCL scale resources and tuning name mapping',
        '// Note: sclbundle.go is auto-generated - do not modify it directly',
        '// This file is also auto-generated by utils/generate-scl.py',
        '',
        '// ScaleInfo contains metadata and resource for an SCL scale',
        'type ScaleInfo struct {',
        '\tFilename string',
        '\tResource *fyne.StaticResource',
        '}',
        '',
        '// AvailableScales maps user-friendly tuning names to scale information',
        '// Use the keys of this map to populate dropdown menus',
        'var AvailableScales = map[string]ScaleInfo{',
    ]
    
    # Add tuning name to ScaleInfo mappings (sorted by name for consistency)
    for tuning_name in sorted(tuning_map.keys()):
        filename = tuning_map[tuning_name]
        internal_name = filename_to_resource_name(filename)
        # Escape quotes in tuning name
        escaped_name = tuning_name.replace('"', '\\"')
        lines.append(f'\t"{escaped_name}": {{Filename: "{filename}", Resource: {internal_name}}},')
    
    lines.append('}')
    lines.append('')
    
    # Add default scale name (find the name that maps to default_scale)
    default_name = None
    for name, filename in tuning_map.items():
        if filename == default_scale:
            default_name = name
            break
    
    if default_name:
        escaped_default = default_name.replace('"', '\\"')
        lines.append(f'// DefaultScaleName is the default tuning name')
        lines.append(f'var DefaultScaleName = "{escaped_default}"')
    else:
        lines.append(f'// DefaultScaleName is the default tuning name')
        lines.append(f'var DefaultScaleName = "12-TET"')
    
    lines.append('')
    
    # Write the file
    content = '\n'.join(lines)
    resources_file.write_text(content, encoding='utf-8')
    
    print(f"\n✓ Generated {RESOURCES_FILENAME}")
    print(f"  Location: {resources_file}")
    print(f"  Created map with {len(tuning_map)} tuning names")
    print(f"  Default scale: {default_name if default_name else default_scale}")


def main():
    """Main execution function."""
    # Get project root
    project_root = get_project_root()
    print(f"Project root: {project_root}")
    
    # Construct paths
    output_directory = project_root / OUTPUT_DIRECTORY
    output_file = output_directory / TARGET_FILENAME
    
    # Verify output directory exists
    if not output_directory.exists():
        print(f"Error: Output directory does not exist: {output_directory}")
        sys.exit(1)
    
    print(f"SCL directory: {output_directory}")
    
    # Collect all SCL files from the directory
    scl_files = sorted([f.name for f in output_directory.glob("*.scl")])
    
    if not scl_files:
        print(f"Error: No SCL files found in {output_directory}")
        sys.exit(1)
    
    print(f"Found {len(scl_files)} SCL files: {', '.join(scl_files)}\n")
    
    # Remove existing output file if it exists
    if output_file.exists():
        output_file.unlink()
        print(f"Removed existing {TARGET_FILENAME}")
    
    # Change to the output directory
    os.chdir(output_directory)
    print(f"Changed directory to: {output_directory}\n")
    
    # Bundle SCL files
    for index, scl_file in enumerate(scl_files):
        is_first = (index == 0)
        
        # Build fyne bundle command
        cmd = ["fyne", "bundle", "-package", TARGET_PACKAGE]
        
        if not is_first:
            cmd.append("-append")
        
        # Output file in same directory
        cmd.extend(["-o", TARGET_FILENAME, scl_file])
        
        # Execute command
        print(f"Bundling {scl_file}{'...' if is_first else ' (append)...'}")
        try:
            result = subprocess.run(cmd, check=True, capture_output=True, text=True)
            if result.stdout:
                print(result.stdout)
        except subprocess.CalledProcessError as e:
            print(f"Error bundling {scl_file}: {e.stderr}")
            sys.exit(1)
    
    print(f"\n✓ Successfully generated {TARGET_FILENAME}")
    print(f"  Location: {output_file}")
    print(f"  Bundled {len(scl_files)} SCL scale files")
    
    # Generate scl_resources.go
    generate_resources_file(scl_files, output_directory, DEFAULT_SCALE)


if __name__ == "__main__":
    main()
