package logic

import "fyne.io/fyne/v2"

// Exported SCL scale resources (wrappers around bundled resources from sclbundle.go)
// Note: sclbundle.go is auto-generated - do not modify it directly
// This file is also auto-generated by utils/generate-scl.py
var (
	Resource1231Scl = resource1231Scl
	Resource1931Scl = resource1931Scl
	Resource2460Scl = resource2460Scl
	Resource79159Scl = resource79159Scl
	ResourceAlvespelogScl = resourceAlvespelogScl
	ResourceAlvesslendroScl = resourceAlvesslendroScl
	ResourceArabicbayatiandbayatiShuriondScl = resourceArabicbayatiandbayatiShuriondScl
	ResourceArabichuzamoneScl = resourceArabichuzamoneScl
	ResourceArabicrastoncScl = resourceArabicrastoncScl
	ResourceBarnesScl = resourceBarnesScl
	ResourceBemetzrieder2Scl = resourceBemetzrieder2Scl
	ResourceBohlenPScl = resourceBohlenPScl
	ResourceCarlosalphaScl = resourceCarlosalphaScl
	ResourceCarlossuperScl = resourceCarlossuperScl
	ResourceChinluScl = resourceChinluScl
	ResourceChinshierluScl = resourceChinshierluScl
	ResourceCorrette3Scl = resourceCorrette3Scl
	ResourceDudonbyzantineScl = resourceDudonbyzantineScl
	ResourceDudonwerckmeister3ebScl = resourceDudonwerckmeister3ebScl
	ResourceEulerScl = resourceEulerScl
	ResourceEulerdiatScl = resourceEulerdiatScl
	ResourceFokker53Scl = resourceFokker53Scl
	ResourceHirajoshiScl = resourceHirajoshiScl
	ResourceIndianScl = resourceIndianScl
	ResourceIndian12Scl = resourceIndian12Scl
	ResourceJi12Scl = resourceJi12Scl
	ResourceKellnerScl = resourceKellnerScl
	ResourceKepler1Scl = resourceKepler1Scl
	ResourceKepler2Scl = resourceKepler2Scl
	ResourceKirnberger1Scl = resourceKirnberger1Scl
	ResourceKirnberger2Scl = resourceKirnberger2Scl
	ResourceKirnberger3Scl = resourceKirnberger3Scl
	ResourceLehman1Scl = resourceLehman1Scl
	ResourceLehman2Scl = resourceLehman2Scl
	ResourceMiracle1Scl = resourceMiracle1Scl
	ResourceNeidhardt1Scl = resourceNeidhardt1Scl
	ResourceNeidhardt3Scl = resourceNeidhardt3Scl
	ResourcePartch39Scl = resourcePartch39Scl
	ResourcePartch41Scl = resourcePartch41Scl
	ResourcePtolemyScl = resourcePtolemyScl
	ResourcePyth12Scl = resourcePyth12Scl
	ResourceRameauScl = resourceRameauScl
	ResourceSelisirScl = resourceSelisirScl
	ResourceTet12Scl = resourceTet12Scl
	ResourceWilson31Scl = resourceWilson31Scl
	ResourceYoungScl = resourceYoungScl
)

// DefaultScale is the default SCL scale (tet-12.scl)
var DefaultScale = ResourceTet12Scl

// Ensure variables are of correct type at compile time
var _ *fyne.StaticResource = Resource1231Scl
var _ *fyne.StaticResource = DefaultScale
