package logic

import "fyne.io/fyne/v2"

// SCL scale resources and tuning name mapping
// Note: sclbundle.go is auto-generated - do not modify it directly
// This file is also auto-generated by utils/generate-scl.py

// ScaleInfo contains metadata and resource for an SCL scale
type ScaleInfo struct {
	Filename string
	Resource *fyne.StaticResource
}

// AvailableScales maps user-friendly tuning names to scale information
// Use the keys of this map to populate dropdown menus
var AvailableScales = map[string]ScaleInfo{
	"12 and 15-tET mixed. Novaro (1951)": {Filename: "24-60.scl", Resource: resource2460Scl},
	"12 out of 31-tET, meantone Eb-G#": {Filename: "12-31.scl", Resource: resource1231Scl},
	"12 tone equal temperament": {Filename: "tet-12.scl", Resource: resourceTet12Scl},
	"12-tone Pythagorean scale": {Filename: "pyth_12.scl", Resource: resourcePyth12Scl},
	"13-limit Diamond after Partch, Genesis of a Music, p 454, 2nd edition": {Filename: "partch_41.scl", Resource: resourcePartch41Scl},
	"19 out of 31-tET, meantone Gb-B#": {Filename: "19-31.scl", Resource: resource1931Scl},
	"21 out of 72-tET Pyth. scale \"Miracle/Blackjack\", Keenan & Erlich, TL 2-5-2001": {Filename: "miracle1.scl", Resource: resourceMiracle1Scl},
	"79 out of 159-tET MOS by Ozan Yarman, 79-tone Tuning & Theory For Turkish Maqam Music": {Filename: "79-159.scl", Resource: resource79159Scl},
	"Anton Bemetzrieder temperament nr. 2 (1808), equal to Marpurg T11, Heinrich Laag's temperament and Vallotti in F#": {Filename: "bemetzrieder2.scl", Resource: resourceBemetzrieder2Scl},
	"Arabic Bayati and Bayati-Shuri (Karjighar) with perde dugah on D by Dr. Oz.": {Filename: "arabic_bayati_and_bayati-shuri_on_d.scl", Resource: resourceArabicbayatiandbayatiShuriondScl},
	"Arabic Huzam with perde segah on E by Dr. Oz.": {Filename: "arabic_huzam_on_e.scl", Resource: resourceArabichuzamoneScl},
	"Arabic Rast with perde rast on C by Dr. Ozan Yarman": {Filename: "arabic_rast_on_c.scl", Resource: resourceArabicrastoncScl},
	"Basic JI with 7-limit tritone. Robert Rich: Geometry": {Filename: "ji_12.scl", Resource: resourceJi12Scl},
	"Bill Alves JI Pelog, 1/1 vol.9 no.4, 1997. 1/1=293.33 Hz": {Filename: "alves_pelog.scl", Resource: resourceAlvespelogScl},
	"Bill Alves, slendro for Gender Barung, 1/1 vol.9 no.4, 1997. 1/1=282.86 Hz": {Filename: "alves_slendro.scl", Resource: resourceAlvesslendroScl},
	"Bradley Lehman Bach squiggle keyboard temperament II (2005)": {Filename: "lehman2.scl", Resource: resourceLehman2Scl},
	"Bradley Lehman Bach temperament I (2005)": {Filename: "lehman1.scl", Resource: resourceLehman1Scl},
	"Byzantine scale, JI interpretation and -c extrapolation of turkish Hijaz in C": {Filename: "dudon_byzantine.scl", Resource: resourceDudonbyzantineScl},
	"Carlos Super Just": {Filename: "carlos_super.scl", Resource: resourceCarlossuperScl},
	"Chinese L scale by Huai Nan zi, Han era. Pre Amiot 1780, Kurt Reinhard": {Filename: "chin_lu.scl", Resource: resourceChinluScl},
	"Corrette's monochord (1753), also Marpurg 4, Yamaha Pure Minor and by Etienne Louli (1696)": {Filename: "corrette3.scl", Resource: resourceCorrette3Scl},
	"Euler's Monochord (a mode of Ellis's duodene) (1739), genus [33355]": {Filename: "euler.scl", Resource: resourceEulerScl},
	"Euler's genus diatonicum veterum correctum, 8-tone triadic cluster 4:5:6, genus [3335]": {Filename: "euler_diat.scl", Resource: resourceEulerdiatScl},
	"Fokker's 53-tone system, degree 37 has alternatives": {Filename: "fokker_53.scl", Resource: resourceFokker53Scl},
	"Gamelan semara pagulingan, Bali. Pagan Kelod": {Filename: "selisir.scl", Resource: resourceSelisirScl},
	"Harmonic equal-beating version of the famous well-temperament (2006)": {Filename: "dudon_werckmeister3_eb.scl", Resource: resourceDudonwerckmeister3ebScl},
	"Herbert Anton Kellner's Bach tuning. 5 1/5 Pyth. comma and 7 pure fifths": {Filename: "kellner.scl", Resource: resourceKellnerScl},
	"Indian shruti scale": {Filename: "indian.scl", Resource: resourceIndianScl},
	"John Barnes' temperament (1977) made after analysis of Wohltemperierte Klavier, 1/6 P": {Filename: "barnes.scl", Resource: resourceBarnesScl},
	"Kepler's Monochord no.1, Harmonices Mundi (1619)": {Filename: "kepler1.scl", Resource: resourceKepler1Scl},
	"Kepler's Monochord no.2": {Filename: "kepler2.scl", Resource: resourceKepler2Scl},
	"Kirnberger 2: 1/2 synt. comma. \"Die Kunst des reinen Satzes\" (1774)": {Filename: "kirnberger2.scl", Resource: resourceKirnberger2Scl},
	"Kirnberger 3: 1/4 synt. comma (1744)": {Filename: "kirnberger3.scl", Resource: resourceKirnberger3Scl},
	"Kirnbergersche Temperatur (1766). Also 12 Indian shrutis": {Filename: "kirnberger1.scl", Resource: resourceKirnberger1Scl},
	"Neidhardt I temperament (1724). Also Trost 3": {Filename: "neidhardt1.scl", Resource: resourceNeidhardt1Scl},
	"Neidhardt III temperament (1724) 'groe Stadt'": {Filename: "neidhardt3.scl", Resource: resourceNeidhardt3Scl},
	"North Indian Gamut, modern Hindustani gamut out of 22 or more shrutis": {Filename: "indian_12.scl", Resource: resourceIndian12Scl},
	"Observed Japanese pentatonic koto scale. Helmholtz/Ellis p.519, nr.112": {Filename: "hirajoshi.scl", Resource: resourceHirajoshiScl},
	"Old Chinese L scale, from http://en.wikipedia.org/wiki/Shi_Er_L%C3%BC": {Filename: "chin_shierlu.scl", Resource: resourceChinshierluScl},
	"Ptolemy's Intense Diatonic Syntonon, also Zarlino's scale": {Filename: "ptolemy.scl", Resource: resourcePtolemyScl},
	"Rameau's modified meantone temperament (1725)": {Filename: "rameau.scl", Resource: resourceRameauScl},
	"See Bohlen, H. 13-Tonstufen in der Duodezime, Acustica 39: 76-86 (1978)": {Filename: "bohlen-p.scl", Resource: resourceBohlenPScl},
	"Thomas Young well temperament (1807), also Luigi Malerbi nr.2 (1794)": {Filename: "young.scl", Resource: resourceYoungScl},
	"Ur-Partch Keyboard 39 tones, published in Interval": {Filename: "partch_39.scl", Resource: resourcePartch39Scl},
	"Wendy Carlos' Alpha scale with perfect fifth divided in nine": {Filename: "carlos_alpha.scl", Resource: resourceCarlosalphaScl},
	"Wilson 11-limit 31-tone scale XH 3, 1975": {Filename: "wilson_31.scl", Resource: resourceWilson31Scl},
}

// DefaultScaleName is the default tuning name
var DefaultScaleName = "12 tone equal temperament"
