// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package logic

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed 12-31.scl
var resource1231SclData []byte
var resource1231Scl = &fyne.StaticResource{
	StaticName:    "12-31.scl",
	StaticContent: resource1231SclData,
}

//go:embed 19-31.scl
var resource1931SclData []byte
var resource1931Scl = &fyne.StaticResource{
	StaticName:    "19-31.scl",
	StaticContent: resource1931SclData,
}

//go:embed 24-60.scl
var resource2460SclData []byte
var resource2460Scl = &fyne.StaticResource{
	StaticName:    "24-60.scl",
	StaticContent: resource2460SclData,
}

//go:embed 79-159.scl
var resource79159SclData []byte
var resource79159Scl = &fyne.StaticResource{
	StaticName:    "79-159.scl",
	StaticContent: resource79159SclData,
}

//go:embed alves_pelog.scl
var resourceAlvespelogSclData []byte
var resourceAlvespelogScl = &fyne.StaticResource{
	StaticName:    "alves_pelog.scl",
	StaticContent: resourceAlvespelogSclData,
}

//go:embed alves_slendro.scl
var resourceAlvesslendroSclData []byte
var resourceAlvesslendroScl = &fyne.StaticResource{
	StaticName:    "alves_slendro.scl",
	StaticContent: resourceAlvesslendroSclData,
}

//go:embed arabic_bayati_and_bayati-shuri_on_d.scl
var resourceArabicbayatiandbayatiShuriondSclData []byte
var resourceArabicbayatiandbayatiShuriondScl = &fyne.StaticResource{
	StaticName:    "arabic_bayati_and_bayati-shuri_on_d.scl",
	StaticContent: resourceArabicbayatiandbayatiShuriondSclData,
}

//go:embed arabic_huzam_on_e.scl
var resourceArabichuzamoneSclData []byte
var resourceArabichuzamoneScl = &fyne.StaticResource{
	StaticName:    "arabic_huzam_on_e.scl",
	StaticContent: resourceArabichuzamoneSclData,
}

//go:embed arabic_rast_on_c.scl
var resourceArabicrastoncSclData []byte
var resourceArabicrastoncScl = &fyne.StaticResource{
	StaticName:    "arabic_rast_on_c.scl",
	StaticContent: resourceArabicrastoncSclData,
}

//go:embed barnes.scl
var resourceBarnesSclData []byte
var resourceBarnesScl = &fyne.StaticResource{
	StaticName:    "barnes.scl",
	StaticContent: resourceBarnesSclData,
}

//go:embed bemetzrieder2.scl
var resourceBemetzrieder2SclData []byte
var resourceBemetzrieder2Scl = &fyne.StaticResource{
	StaticName:    "bemetzrieder2.scl",
	StaticContent: resourceBemetzrieder2SclData,
}

//go:embed bohlen-p.scl
var resourceBohlenPSclData []byte
var resourceBohlenPScl = &fyne.StaticResource{
	StaticName:    "bohlen-p.scl",
	StaticContent: resourceBohlenPSclData,
}

//go:embed carlos_alpha.scl
var resourceCarlosalphaSclData []byte
var resourceCarlosalphaScl = &fyne.StaticResource{
	StaticName:    "carlos_alpha.scl",
	StaticContent: resourceCarlosalphaSclData,
}

//go:embed carlos_super.scl
var resourceCarlossuperSclData []byte
var resourceCarlossuperScl = &fyne.StaticResource{
	StaticName:    "carlos_super.scl",
	StaticContent: resourceCarlossuperSclData,
}

//go:embed chin_lu.scl
var resourceChinluSclData []byte
var resourceChinluScl = &fyne.StaticResource{
	StaticName:    "chin_lu.scl",
	StaticContent: resourceChinluSclData,
}

//go:embed chin_shierlu.scl
var resourceChinshierluSclData []byte
var resourceChinshierluScl = &fyne.StaticResource{
	StaticName:    "chin_shierlu.scl",
	StaticContent: resourceChinshierluSclData,
}

//go:embed corrette3.scl
var resourceCorrette3SclData []byte
var resourceCorrette3Scl = &fyne.StaticResource{
	StaticName:    "corrette3.scl",
	StaticContent: resourceCorrette3SclData,
}

//go:embed dudon_byzantine.scl
var resourceDudonbyzantineSclData []byte
var resourceDudonbyzantineScl = &fyne.StaticResource{
	StaticName:    "dudon_byzantine.scl",
	StaticContent: resourceDudonbyzantineSclData,
}

//go:embed dudon_werckmeister3_eb.scl
var resourceDudonwerckmeister3ebSclData []byte
var resourceDudonwerckmeister3ebScl = &fyne.StaticResource{
	StaticName:    "dudon_werckmeister3_eb.scl",
	StaticContent: resourceDudonwerckmeister3ebSclData,
}

//go:embed euler.scl
var resourceEulerSclData []byte
var resourceEulerScl = &fyne.StaticResource{
	StaticName:    "euler.scl",
	StaticContent: resourceEulerSclData,
}

//go:embed euler_diat.scl
var resourceEulerdiatSclData []byte
var resourceEulerdiatScl = &fyne.StaticResource{
	StaticName:    "euler_diat.scl",
	StaticContent: resourceEulerdiatSclData,
}

//go:embed fokker_53.scl
var resourceFokker53SclData []byte
var resourceFokker53Scl = &fyne.StaticResource{
	StaticName:    "fokker_53.scl",
	StaticContent: resourceFokker53SclData,
}

//go:embed hirajoshi.scl
var resourceHirajoshiSclData []byte
var resourceHirajoshiScl = &fyne.StaticResource{
	StaticName:    "hirajoshi.scl",
	StaticContent: resourceHirajoshiSclData,
}

//go:embed indian.scl
var resourceIndianSclData []byte
var resourceIndianScl = &fyne.StaticResource{
	StaticName:    "indian.scl",
	StaticContent: resourceIndianSclData,
}

//go:embed indian_12.scl
var resourceIndian12SclData []byte
var resourceIndian12Scl = &fyne.StaticResource{
	StaticName:    "indian_12.scl",
	StaticContent: resourceIndian12SclData,
}

//go:embed ji_12.scl
var resourceJi12SclData []byte
var resourceJi12Scl = &fyne.StaticResource{
	StaticName:    "ji_12.scl",
	StaticContent: resourceJi12SclData,
}

//go:embed kellner.scl
var resourceKellnerSclData []byte
var resourceKellnerScl = &fyne.StaticResource{
	StaticName:    "kellner.scl",
	StaticContent: resourceKellnerSclData,
}

//go:embed kepler1.scl
var resourceKepler1SclData []byte
var resourceKepler1Scl = &fyne.StaticResource{
	StaticName:    "kepler1.scl",
	StaticContent: resourceKepler1SclData,
}

//go:embed kepler2.scl
var resourceKepler2SclData []byte
var resourceKepler2Scl = &fyne.StaticResource{
	StaticName:    "kepler2.scl",
	StaticContent: resourceKepler2SclData,
}

//go:embed kirnberger1.scl
var resourceKirnberger1SclData []byte
var resourceKirnberger1Scl = &fyne.StaticResource{
	StaticName:    "kirnberger1.scl",
	StaticContent: resourceKirnberger1SclData,
}

//go:embed kirnberger2.scl
var resourceKirnberger2SclData []byte
var resourceKirnberger2Scl = &fyne.StaticResource{
	StaticName:    "kirnberger2.scl",
	StaticContent: resourceKirnberger2SclData,
}

//go:embed kirnberger3.scl
var resourceKirnberger3SclData []byte
var resourceKirnberger3Scl = &fyne.StaticResource{
	StaticName:    "kirnberger3.scl",
	StaticContent: resourceKirnberger3SclData,
}

//go:embed lehman1.scl
var resourceLehman1SclData []byte
var resourceLehman1Scl = &fyne.StaticResource{
	StaticName:    "lehman1.scl",
	StaticContent: resourceLehman1SclData,
}

//go:embed lehman2.scl
var resourceLehman2SclData []byte
var resourceLehman2Scl = &fyne.StaticResource{
	StaticName:    "lehman2.scl",
	StaticContent: resourceLehman2SclData,
}

//go:embed miracle1.scl
var resourceMiracle1SclData []byte
var resourceMiracle1Scl = &fyne.StaticResource{
	StaticName:    "miracle1.scl",
	StaticContent: resourceMiracle1SclData,
}

//go:embed neidhardt1.scl
var resourceNeidhardt1SclData []byte
var resourceNeidhardt1Scl = &fyne.StaticResource{
	StaticName:    "neidhardt1.scl",
	StaticContent: resourceNeidhardt1SclData,
}

//go:embed neidhardt3.scl
var resourceNeidhardt3SclData []byte
var resourceNeidhardt3Scl = &fyne.StaticResource{
	StaticName:    "neidhardt3.scl",
	StaticContent: resourceNeidhardt3SclData,
}

//go:embed partch_39.scl
var resourcePartch39SclData []byte
var resourcePartch39Scl = &fyne.StaticResource{
	StaticName:    "partch_39.scl",
	StaticContent: resourcePartch39SclData,
}

//go:embed partch_41.scl
var resourcePartch41SclData []byte
var resourcePartch41Scl = &fyne.StaticResource{
	StaticName:    "partch_41.scl",
	StaticContent: resourcePartch41SclData,
}

//go:embed ptolemy.scl
var resourcePtolemySclData []byte
var resourcePtolemyScl = &fyne.StaticResource{
	StaticName:    "ptolemy.scl",
	StaticContent: resourcePtolemySclData,
}

//go:embed pyth_12.scl
var resourcePyth12SclData []byte
var resourcePyth12Scl = &fyne.StaticResource{
	StaticName:    "pyth_12.scl",
	StaticContent: resourcePyth12SclData,
}

//go:embed rameau.scl
var resourceRameauSclData []byte
var resourceRameauScl = &fyne.StaticResource{
	StaticName:    "rameau.scl",
	StaticContent: resourceRameauSclData,
}

//go:embed selisir.scl
var resourceSelisirSclData []byte
var resourceSelisirScl = &fyne.StaticResource{
	StaticName:    "selisir.scl",
	StaticContent: resourceSelisirSclData,
}

//go:embed tet-12.scl
var resourceTet12SclData []byte
var resourceTet12Scl = &fyne.StaticResource{
	StaticName:    "tet-12.scl",
	StaticContent: resourceTet12SclData,
}

//go:embed wilson_31.scl
var resourceWilson31SclData []byte
var resourceWilson31Scl = &fyne.StaticResource{
	StaticName:    "wilson_31.scl",
	StaticContent: resourceWilson31SclData,
}

//go:embed young.scl
var resourceYoungSclData []byte
var resourceYoungScl = &fyne.StaticResource{
	StaticName:    "young.scl",
	StaticContent: resourceYoungSclData,
}
