package ui

import "fyne.io/fyne/v2"

// Exported icon resources (wrappers around bundled resources from tabicons.go)
// Note: tabicons.go is auto-generated - do not modify it directly
// This file is also auto-generated by utils/generate-tabicons.py
var (
	ResourceDelaySvg        = resourceDelaySvg
	ResourceFreq2noteSvg    = resourceFreq2noteSvg
	ResourceNote2freqSvg    = resourceNote2freqSvg
	ResourceSamplelengthSvg = resourceSamplelengthSvg
	ResourceTempochangeSvg  = resourceTempochangeSvg
	ResourceTimecodeSvg     = resourceTimecodeSvg
)

// Ensure variables are of correct type at compile time
var _ *fyne.StaticResource = ResourceDelaySvg
