// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed alignmentdelay.svg
var resourceAlignmentdelaySvgData []byte
var resourceAlignmentdelaySvg = &fyne.StaticResource{
	StaticName:    "alignmentdelay.svg",
	StaticContent: resourceAlignmentdelaySvgData,
}

//go:embed delay.svg
var resourceDelaySvgData []byte
var resourceDelaySvg = &fyne.StaticResource{
	StaticName:    "delay.svg",
	StaticContent: resourceDelaySvgData,
}

//go:embed freq2note.svg
var resourceFreq2noteSvgData []byte
var resourceFreq2noteSvg = &fyne.StaticResource{
	StaticName:    "freq2note.svg",
	StaticContent: resourceFreq2noteSvgData,
}

//go:embed note2freq.svg
var resourceNote2freqSvgData []byte
var resourceNote2freqSvg = &fyne.StaticResource{
	StaticName:    "note2freq.svg",
	StaticContent: resourceNote2freqSvgData,
}

//go:embed samplelength.svg
var resourceSamplelengthSvgData []byte
var resourceSamplelengthSvg = &fyne.StaticResource{
	StaticName:    "samplelength.svg",
	StaticContent: resourceSamplelengthSvgData,
}

//go:embed tempochange.svg
var resourceTempochangeSvgData []byte
var resourceTempochangeSvg = &fyne.StaticResource{
	StaticName:    "tempochange.svg",
	StaticContent: resourceTempochangeSvgData,
}

//go:embed timecode.svg
var resourceTimecodeSvgData []byte
var resourceTimecodeSvg = &fyne.StaticResource{
	StaticName:    "timecode.svg",
	StaticContent: resourceTimecodeSvgData,
}
